version: 0.2
env:
  shell: bash
phases: 
  pre_build: 
    commands: 
    - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain agama --domain-owner 270167558056 --query authorizationToken --output text --region us-east-1`
  build: 
    commands: 
    - echo Build started on `date` 
    - mvn clean deploy