version: 0.2
env:
  shell: bash
phases: 
  pre_build: 
    commands: 
    - curl -O https://download.java.net/java/GA/jdk18/43f95e8614114aeaa8e8a5fcf20a682d/36/GPL/openjdk-18_linux-x64_bin.tar.gz
    - curl -O https://dlcdn.apache.org/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.tar.gz
    - tar xvf openjdk-18_linux-x64_bin.tar.gz
    - sudo mv jdk-18 /opt/
    - export JAVA_HOME=/opt/jdk-18
    - export PATH=${JAVA_HOME}/bin:${PATH}
    - tar xvf apache-maven-3.8.6-bin.tar.gz
    - sudo mv apache-maven-3.8.6 /opt/
    - export M2_HOME=/opt/apache-maven-3.8.6
    - export PATH=${M2_HOME}/bin:${PATH}
    - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain agama --domain-owner 270167558056 --query authorizationToken --output text --region us-east-1`
    - echo $CODEARTIFACT_AUTH_TOKEN
    - . ~/.profile    
  build: 
    commands: 
    - echo Build started on `date`
    - cp ./settings.xml /root/.m2/settings.xml 
    - mvn clean deploy